### ISSUE TITLE
Mistake in default settings?

### ISSUE THREAD

**Issue by MaartenvanDorp** [TheoChem-VU/TCutility#113]
After running to generate several geometry optimization jobs from a directory of .xyz files the following errorcode was returned:

 ERROR: Input error: value "CalculateWithFasterEngine" found in line 7 for multiple choice key "geometryoptimization%initialhessian%type" is not an allowed choice

Settings for the mentioned key were not specified in the script. Possibly a mistake in the default settings?

[run.txt](https://github.com/TheoChem-VU/TCutility/files/14168769/run.txt)

**Comment by YHordijk** [comment]
This was fixed in update [v0.8.2](https://github.com/TheoChem-VU/TCutility/releases/tag/v0.8.2). Please run `pip install --upgrade TCutility` to update your installation
