### ISSUE TITLE
Add command line scripts to the package

### ISSUE THREAD

**Issue by SiebeLeDe** [TheoChem-VU/TCutility#154]
For example, a script to concatenate irc files

**Comment by YHordijk** [comment]
I propose we also add a script to quickly optimize a molecule.
For example,
`optimize mol.xyz --level BLYP-D3(BJ)/TZ2P`
should start a job and then write the optimized molecule to `optimized_mol.xyz` or something like that.

By default it can use GFN1-xTB.

**Comment by SiebeLeDe** [comment]
Nice idea! I see that I did not yet push the branch. I will let you know when I do
