### ISSUE TITLE
Interpolation module

### ISSUE THREAD

**Issue by YHordijk** [TheoChem-VU/TCutility#155]
Sometimes it is useful to be able to perform interpolations on your data. For example, if you want to know the value of some kind of property at a consistent geometry you can either do a SP calculation at that geometry or do an interpolation of some kind.

I propose we add a module that adds some functions/classes that handle interpolations for us. This can then be used in PyOrb or PyFrag.

**Comment by SiebeLeDe** [comment]
Interpolation is really easy using scipy (interpolate Splines) and pandas (store results in a dataframe. 
I plan to implement it in PyFrag. 

See here for an implementation

https://github.com/SiebeLeDe/pyfrag_plot/blob/main/src/pyfrag_plotter/interpolate.py

**Comment by YHordijk** [comment]
Perfect! 
I will implement the scipy functions in TCintegral as well.
For now I will close this issue and branch as they are not needed anymore.
