### ISSUE TITLE
Improve support for jobs with History

### ISSUE THREAD

**Issue by YHordijk** [TheoChem-VU/TCutility#18]
Currently jobs such as IRC and PES-scans are not fully read. I propose to add some variables to help analyse them.
 - Read indices of accepted geometries
 - Add variable for energy landscape of accepted geometries
 - Add coordinates of accepted geometries
 - Read and store reaction coordinate along accepted geometries

**Comment by SiebeLeDe** [comment]
Check the plams implementations: 

[energy landscape](https://www.scm.com/doc/plams/interfaces/ams.html#scm.plams.interfaces.adfsuite.ams.AMSResults.get_energy_landscape)
[history property](https://www.scm.com/doc/plams/interfaces/ams.html#scm.plams.interfaces.adfsuite.ams.AMSResults.get_history_property)
[history variables]
(https://www.scm.com/doc/plams/interfaces/ams.html#scm.plams.interfaces.adfsuite.ams.AMSResults.get_history_variables)

If your implementations achieve the same thing, I wonder if it is necessary to implement it in tcutility

**Comment by YHordijk** [comment]
I prefer to avoid the plams.Results objects as they require loading the job using plams, which in turn requires (I think) the job to be saved as a .dill file. It also requires initializing plams as it requires a jobmanager object. Everytime you initialize plams it will also create a directory for you, so we have to keep track of it and then delete it later. This will basically require us to wrap the whole program in a try/except block, otherwise we might not be able to delete it if the program crashes. Also, we will then have a TCutility result and plams result object, which again requires a lot more bookkeeping for us and loads everything twice.

In any case, we already have support for History variables that is easy to use (see [this postscript](https://github.com/TheoChem-VU/TCutility/blob/8e000c92c6ba269171a84f63a3ccb29ef258d630/src/tcutility/job/postscripts/write_amv.py)). But we might implement some plotting functions/drawing of molecules etc. For now I will close this until we want to work on something more specific related to the history variables.
