### ISSUE TITLE
Add option to perform electrostatic decomposition calculation for ADFFragmentJob calculations

### ISSUE THREAD

**Issue by YHordijk** [TheoChem-VU/TCutility#279]
Looking at electrostatic decompositions can be useful for uncovering the origin of the electrostatic interactions. According to the handbook, the way to do it is to enable a few options in ADF, namely the `STOFIT` and `PRINT ELSTAT` options as well as setting the quality of the BeckeGrid to `Excellent`. These settings should be used for a new calculations, as the handbook recommends disabling the `STOFIT` option for regular energy decomposition analyses.
Doing this extra calculation should yield 4 new terms that may be useful for the chemist.

**Comment by SiebeLeDe** [comment]
Good idea! Do not forget to take into account the charges of the fragments. The elstat decomp requires fragment calculations where the charge is equal to the number of electrons (so no electrons for the N-e or e-N term). However, we should still keep the charges of the initial fragments where the charge does not have to be equal to the number of charge, for example

frag1: Na (11e) = charge 11
frag2: Cl (17e, but 18e as anion) = charge -1
