### ISSUE TITLE
Read VibrationalAnalysis jobs has a different folder structure

### ISSUE THREAD

**Issue by YHordijk** [TheoChem-VU/TCutility#28]
When performing a VibrationalAnalysis job using ADF there is no adf.rkf created, only the ams.rkf. All info is contained in ams.rkf, however TCutility will try to read from adf.rkf. 

- We should add a check for the type of task used and then depending on  the task read from different files.
- Separate the reading of vibrational properties in reader.adf.get_properties into a new function that takes a reader object as argument and then simply supply the ams.rkf when the task equals VibrationalAnalysis

**Comment by ToriGijzen** [comment]
NOTE: In the case of LT's and IRC's also only ams.rkf is created
