### ISSUE TITLE
Automatic publishing to PyPi when a new release is made

### ISSUE THREAD

**Issue by YHordijk** [TheoChem-VU/TCutility#4]
We should create a workflow that automatically uploads new releases to PyPi. 
One usefull github action: https://github.com/marketplace/actions/pypi-publish

**Comment by SiebeLeDe** [comment]
We automate it, but we need an TheoCheM email account for making a PyPI account. When I know that, I can get the private token and link this repo to PyPI with the github workflow

**Comment by SiebeLeDe** [comment]
Implemented
