### ISSUE TITLE
Pathfunc module

### ISSUE THREAD

**Issue by YHordijk** [TheoChem-VU/TCutility#85]
In preparation for some of the code related to the new job-running module and subsequent analysis, I think it would nice to include some functionality related to path. For example, getting all subdirectories in a path. Getting new versions of paths (e.g. suffixed with .002). I already have some functionality in [`yutility.pathfunc`](https://github.com/YHordijk/yutility/blob/master/pathfunc.py) that I will be porting over to TCutility.

Some useful functions:
# get_size(path)
Returns the file sizes of the whole tree given in path.

# get_path_versions(path)
Returns all paths that correspond to path, but include its versions. 
E.g. calling `get_path_versions('root/dir_or_file')` with the following file-structure
```
root
|- dir_or_file
|- dir_or_file.002
|- dir_or_file.003
|- ...
|- dir_or_file.n
```
will return all files starting with `root/dir_or_file`

# next_path_version(path)
Returns a new path with a version number attached to the end that is not yet taken.
E.g. calling `next_path_version('root/dir_or_file')` with the following file-structure
```
root
|- dir_or_file
|- dir_or_file.002
|- dir_or_file.003
```
returns `root/dir_or_file.004`.

# split_all(path)
Returns a list of all path parts, unlike os.path.split, which only splits on the last slash/backslash.

# get_subdirectories(root)
Returns a list of all subdirectories in the root.

# match_paths(root, pattern)
This is in my opinion the most important function. It will return a list of subdirectories of root matching a certain pattern, and also return information related to the pattern.
E.g. given the following file-structure
```
root
|- NH3-BH3
    |- BLYP_QZ4P
       |- extra_dir
       |- blablabla
    |- BLYP_TZ2P
       |- another_dir
    |- M06-2X_TZ2P
|- SN2
    |- BLYP_TZ2P
    |- M06-2X_TZ2P
       |- M06-2X_TZ2P
```
and calling `match_paths('root', '{system}/{functional}_{basis_set}')` will return a tuple containing a list of subdirectories that match the pattern. We can print the results in a pretty way:

```python
from tcutility import log

dirs, groups = match_paths('pathfunc_test', '{system}/{functional}_{basis_set}')
group_keys = groups.keys()

rows = []
for i, d in enumerate(dirs):
    rows.append([d] + [groups[key][i] for key in group_keys])
log.table(rows, ['Directory'] + list(group_keys))
```
will print

```
[2024/01/17 14:39:08] Directory             system    functional   basis_set
[2024/01/17 14:39:08] ───────────────────────────────────────────────────────
[2024/01/17 14:39:08] SN2/M06-2X_TZ2P       SN2       M06-2X       TZ2P     
[2024/01/17 14:39:08] NH3-BH3/BLYP_TZ2P     NH3-BH3   BLYP         TZ2P     
[2024/01/17 14:39:08] NH3-BH3/M06-2X_TZ2P   NH3-BH3   M06-2X       TZ2P     
[2024/01/17 14:39:08] SN2/BLYP_TZ2P         SN2       BLYP         TZ2P     
[2024/01/17 14:39:08] NH3-BH3/BLYP_QZ4P     NH3-BH3   BLYP         QZ4P     
```

Therefore, it ignores extra subdirectories that are not related to your pattern. And it will decompose the subdirectory path into its substituents.

**Comment by SiebeLeDe** [comment]
Need to think about this to the extent of generalizability. You assume with the last function that there is a strict folder make up. Personally, I like to have one directory in which folders exist with all the attributes in it

**Comment by YHordijk** [comment]
Indeed, this is more for when we implement the job module. In that case we will likely have quite structured folders. Then it would be nice to have this method. Also for things such as benchmarks it might be nice to have something like this, so that we can quickly obtain all calculation directories.
